name: Push-to-EC2
on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the files
      uses: actions/checkout@v4

    - name: List files in the current directory
      run: |
        echo "Listando arquivos e diretórios no diretório atual:"
        ls -la
        
    - name: copy file via ssh key
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ec2-user
        port: 22
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "./"
        target: /home/ec2-user
